name: 'Changelog Driven Release'
description: 'Release a new version of your project when you update the changelog'
branding:
  icon: 'award'
  color: 'green'
inputs:
  path:
    description: 'Path to the changelog file'
    required: true
    default: 'CHANGELOG.md'
  draft:
    description: 'Whether the release should be a draft or not'
    required: true
    default: 'true'
  mutable:
    description: 'Whether mutable tags should be updated or not'
    required: true
    default: 'true'
  token:
    description: 'The GitHub token'
    required: true
    default: '${{ github.token }}'
outputs:
  url:
    description: 'The URL of the release'
  tag:
    description: 'The tag of the release'
  tags:
    description: 'The tags of the release'
  body:
    description: 'The body of the release'
runs:
  using: 'node16'
  main: 'index.js'
