name: Release

on:
  workflow_dispatch:
    inputs:
      draft:
        description: 'Whether the release should be a draft or not'
        required: true
        default: 'true'
  push:
    paths: [CHANGELOG.md]
    branches: [main]
  pull_request:
    paths: [CHANGELOG.md]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    uses: ./.github/workflows/pr.yml
