name: Release
on:
  workflow_dispatch:
    inputs:
      draft:
        description: 'Whether the release should be a draft or not'
        required: true
        default: 'true'
  push:
    paths: [CHANGELOG.md]
    branches: [main]
  pull_request:
    paths: [CHANGELOG.md]
    branches: [main]
jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: release
        if: hashFiles('CHANGELOG.md') != ''
        uses: ./
        with:
          path: CHANGELOG.md
          draft: ${{ github.event_name == 'pull_request' || github.event.inputs.draft == 'true' }}
      - if: hashFiles('CHANGELOG.md') != '' && github.event_name == 'pull_request'  && steps.release.outputs.tag != ''
        uses: marocchino/sticky-pull-request-comment@f6a2580ed520ae15da6076e7410b088d1c5dddd9 # v2.7.0
        with:
          header: release
          recreate: true
          message: |
            ## [${{ steps.release.outputs.tag }}](${{ steps.release.outputs.url }})

            ${{ steps.release.outputs.body }}
